imports:
    - converter.yaml

parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Willydamtchou\SymfonyThirdpartyAdapter\:
        resource: '../../'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
